# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-03-12 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clone', '0003_auto_20200308_2346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
